# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, start_date, stop_date):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 360, 60))
        self.label.setObjectName("label")
        self.update_btm = QtWidgets.QPushButton(Dialog)
        self.update_btm.setGeometry(QtCore.QRect(160, 100, 80, 25))
        self.update_btm.setObjectName("update_btm")
        
        self.update_btm.clicked.connect(Dialog.accept)

        self.retranslateUi(Dialog, start_date, stop_date)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, start_date, stop_date):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Search alert"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Your keyword has only {} to {}</span></p><p align=\"center\"><span style=\" font-size:10pt;\">Please search from {} to {}</span></p></body></html>").format(start_date, stop_date, start_date, stop_date))
        self.update_btm.setText(_translate("Dialog", "OK"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, "2021-02-10", "2021-02-11")
    Dialog.show()
    sys.exit(app.exec_())
